### ISSUE TITLE
Another repo

### ISSUE THREAD

**Issue by tfernd** [boringcrypto/boringfusion#1]
You might wanna take a look at https://github.com/tfernd/sd-fused ;) since we are re-implementing the same thing.

**Comment by bartjellema** [comment]
Cool, for me it's been mainly a learning experience, does the fusing help much with performance?

**Comment by tfernd** [comment]
My goal was to make the SD code clear for everyone. With low and high-level code separation so it is easy to read. Because the original code it's not pretty or easy to read at all... :(
A secondary goal is to fuse CUDA kernels for speed improvements (ongoing).

**Comment by bartjellema** [comment]
Yeah, very cool :) ping me on discord if you feel like sharing notes... BoringCrypto#3523
